var g_dictReplace = {
	'pas d\'enc percu': 'pas d\'encombrement perçu',
	'modal ventil': 'modalités ventilatoires',
	'secretions': 'sécrétions',
	'Execution': 'Exécution',
	'execution': 'exécution',
	'encprox': 'encombrement proximal',
	'EAMF4m': 'entretient articulaire et myofascial des 4 membres',
	'expect': 'expectorations',
	'/ESS11': 'équilibre statique stable sous déstabilisations intrinsèques et extrinsèques',
	'/ESS10': 'équilibre statique stable sous déstabilisations intrinsèques mais pas sous déstabilisations extrinsèques',
	'PCCCD': 'précautions complémentaires contact Clostridium Difficile',
	'ABABP': 'attelle BABP',
	'WRVTP': 'travail de recrutement des volumes thoraco-pulmonaires',
	'percu': 'perçu',
	'Sygie': 'sympomatologie',
	'spo2': 'SpO2 moy',
	'RMed': 'rotation médiale',
	'puru': 'purulentes',
	'SAOS ': 'syndrome d\'apnée obstructive du sommeil',
	'ASPL': 'autonome sur le plan locomoteur',
	'LHID': 'lutte contre l\'hyperinflation dynamique',
	'RVTP': 'recrutement des volumes thoraco-pulmonaires',
	'PEEP': 'pression expiratoire positive',
	'ATCD': 'antécédents',
	'AUTO': 'autonome',
	'APLT': 'autonome pour les transferts',
	'ANTe': 'antérieur',
	'ABDL': 'assis bord de lit',
	'CATB': 'cure t\'antibiotiques',
	'bemv': 'bonne exécution des modalités ventilatoires', 
	'pdep': 'pas d\'encombrement perçu',
	'EAMF': 'entretient articulaire et myofascial',
	'POST': 'postérieur',
	'CTSB': 'cervico-thoraco-scapulo-brachial',
	'ACFA': 'arythmie complète par fibrillation atriale',
	'WQQM': 'travail qualitatif et quantitatif de la marche',
	'WESD': 'travail de l\'équilibre statique et dynamique',
	'AOMI': 'artérite oblitérante des membres inférieurs',
	'SDRA': 'syndrome de détresse respiratoire aiguë',
	'ADK': 'adénocarcinome',
	'DRA': 'détresse respiratoire aiguë',
	'AFE': 'accélération du flux expiratoire',
	'ROS': 'réponse aux ordres simples',
	'ROT': 'réflexes ostéo-tendineux',
	'KAA': 'kinésithérapie active aidée',
	'KP': 'kinésithérapie passive',
	'ACR': 'arrêt cardio-respiratoire',
	'AAA': 'anévrisme de l\'aorte abdominale',
	'PTH': 'prothèse totale de hanche',
	'PTG': 'prothèse totale de genou',
	'PTE': 'prothèse totale d\'épaule',
	'SCC': 'sterno-costo-claviculaire',
	'SST': 'scapulo-serrato-thoracique',
	'ATF': 'attelle thermo-formée',
	'LAT': 'latéral',
	'MED': 'médial',
	'ANP': 'apiration naso-pharyngée',
	'AOP': 'aspiration oro-pharyngée',
	'OAP': 'oedeme aigu du poumon',
	'ANT': 'aspiration naso-trachéale',
	'IOT': 'intubation oro-trachéale',
	'INT': 'intubation naso-trachéale',
	'HID': 'hyperinflation dynamique',
	'KRD': 'kinésithérapie respiratoire de drainage',
	'KRI': 'kinésithérapie respiratoire incitative',
	'AAT': 'aide à la toux',
	'AET': 'aspiration endotrachéale',
	'WDT': 'travail des transferts',
	'VVP': 'voie veineuse périphérique',
	'SOH': ' syndrome d\'obésité-hypoventilation',
	'MPA': 'maladie de Parkinson',
	'/ES': 'équilibre statique',
	'/ED': 'équilibre dynamique',
	' R2R': ' rollator 2 roues',
	' R3R': ' rollator 3 roues',
	' R4R': ' rollator 4 roues',
	' CDM': ' cadre de marche',
	'MMC': 'masque à moyenne concentration',
	'TSS': 'tirage supra-sternal',
	'MHC': 'masque à haute concentration',
	'SNG': 'sonde naso-gastrique',
	'WRM': 'travail de renforcement musculaire',
	'RMG': 'renforcement musculaire gymnique',
	'PNO': 'pneumothorax',
	'PNP': 'pneumopathie',
	'CDB': 'collapsus dynamique bronchique',
	'PEC': 'prise en charge',
	'VRE': 'volume de réserve expiratoire',
	'VRI': 'volume de réserve inspiratoire',
	'CPT': 'capacité pulmonaire totale',
	'ATB': 'antibiotique',
	'RAD': 'retour à domicile',
	'ESD': 'équilibre statique et dynamique',
	'SSH': 'sérum salé hypertonique',
	'EVA': 'sur l\'échelle visuelle analogique',
	'PCC': 'précautions complémentaires contact',
	'PCG': 'précautions complémentaires gouttelettes',
	'PCA': 'précautions complémentaires air',
	'PCP': 'précautions complémentaires protectrices',
	'BAV': 'bloc atrio-ventriculaire',
        'WPM': 'travail du périmetre de marche',
	'TMB': 'transfert monobloc',
	'VS([^-])': 'ventilation spontanée$1',
	' LPF': ' lombo-pelvi-fémoral',
	'TD': 'toux dirigée',
	'SB': 'spasticité bronchique',
	'FR': 'fréquence respiratoire',
	'VD': 'ventilation dirigée',
	'TP': 'toux protégée',
        'PB': 'plexus brachial',
        'PL': 'plexus lombal',
        'PS': 'plexus sacral',
	'DC': 'décubitus',
	'PM': 'périmètres de marche',
	'CN': 'canules nasales',
	'TC': 'test de comptage',
	'LC': 'latéro-cubitus',
	'PC': 'pro-cubitus',
	'FC': 'fréquence cardiaque',
	'SN': 'sonde nasale d\'O2',
	'en AA': 'en air ambiant',
	'AA': 'amplitudes articulaires',
        'EN': 'sur l\'échelle numérique',
	' cr ': ' expectorations ',
	'DA': 'drainage autogène',
	'MV': 'murmure vésiculaire',
	'AT': 'aide technique',
	'MI': 'membre inférieur',
	'CS': 'canne simple',
	'CA': 'canne anglaise',
	'CI': 'capacité inspiratoire',
	'VR': 'volume résiduel',
	'D([1-3])': 'degré $1',
	'Vt': 'volume courant',
	'CV': 'capacité vitale',
	'RL': 'rotation latérale',
	'MS': 'membre supérieur',
	'RM': 'renforcement musculaire',
	'MK': 'kinésithérapeute',
	'FP': 'femoro-patellaire',
	'FT': 'femoro-tibial',
	'KR': 'kinésithérapie respiratoire',
	'RX': 'radiographie',
	' CF': ' coxofémoral',
	' GH': ' glénohuméral',
	' D': ' droit',
	' G': ' gauche',
}
